In [101]:
import sqlite3 as sq3
import pandas as pd

# Create your connection.
con = sq3.connect('long_backtest_data.sql')
df = pd.read_sql_query("SELECT * FROM data", con)
con.close()

result = round(df.groupby('symbol').agg(balance=('balance', 'max')),2)
result['gains'] = round(result-10000, 2)
result['percentage'] =  round((result['gains']/10000) * 100, 2)
result["balance"] = result["balance"].map("${:,.0f}".format)

df_summary = result.groupby(['symbol','balance','percentage'])['gains'].sum().sort_values(ascending=False)
df_summary.loc['Grand Total'] = df_summary.sum()
df_summary = df_summary.reset_index()

df_summary['gains'] = df_summary['gains'].map("${:,.0f}".format)

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_rows", None) 

header = 'From: Oct-5 22 To:  Oct-5 24 <br> Inversion: $10,000 c/u <br> stop: close5minSmooth < ema25_5min <br> target: (buying_price-current_price) >= 2<br>'

df_summary.columns = pd.MultiIndex.from_product([['Backtesting'], df_summary.columns])
styler = df_summary.style.set_caption(header).set_table_styles([{
    'selector': 'caption',
    'props': [
        ('color', 'Purple'),
        ('font-size', '15px'),
        ('font-style', 'italic'),
        ('font-weight', 'bold'),
        ('text-align', 'Left')
    ]
}])

display(styler)

In [99]:
import sqlite3 as sq3
import pandas as pd

con = sq3.connect('long_backtest_data.sql')
df = pd.read_sql_query("SELECT * FROM data", con)
con.close()

result = df[df["symbol"]== 'GOOGL']
pd.set_option('display.max_rows', None)
display(result)

,index,datetime,direction,symbol,buy_index,units,buying_price,entry_amount,sell_index,sell_price,exit_amount,gain_or_loss,performance,move,balance,index2
0,0,2022-10-06 12:50:00-04:00,long,GOOGL,118,97,102.20,9913.69,120,102.07,9901.18,-12.51,-0.13,-0.13,9987.49,B
1,1,2022-10-17 12:05:00-04:00,long,GOOGL,655,99,100.24,9924.06,688,100.39,9938.91,14.85,0.15,0.15,10002.34,B
2,2,2022-10-18 11:45:00-04:00,long,GOOGL,705,99,100.64,9963.66,733,100.80,9979.50,15.84,0.16,0.16,10018.18,B
3,3,2022-10-18 15:50:00-04:00,long,GOOGL,754,99,100.63,9962.77,756,100.58,9957.72,-5.05,-0.05,-0.05,10013.13,B
4,4,2022-10-25 11:55:00-04:00,long,GOOGL,1097,96,103.82,9967.01,1102,103.83,9968.06,1.06,0.01,0.01,10014.18,B
5,5,2022-10-25 14:15:00-04:00,long,GOOGL,1125,96,103.64,9949.82,1146,95.79,9196.22,-753.60,-7.57,-7.85,9260.58,B
6,6,2022-11-04 12:40:00-04:00,long,GOOGL,1730,108,85.09,9190.15,1795,87.74,9476.35,286.20,3.11,2.65,9546.78,B
7,7,2022-11-07 13:15:00-05:00,long,GOOGL,1815,108,87.89,9492.55,1886,89.56,9672.91,180.36,1.90,1.67,9727.14,B
8,8,2022-11-10 14:00:00-05:00,long,GOOGL,2058,104,93.52,9726.39,2154,96.49,10035.27,308.88,3.18,2.97,10036.02,B
9,9,2022-11-16 10:45:00-05:00,long,GOOGL,2331,101,98.49,9947.79,2371,99.00,9999.30,51.51,0.52,0.51,10087.53,B
10,10,2022-11-23 09:35:00-05:00,long,GOOGL,2707,103,97.75,10068.56,2733,97.72,10065.47,-3.09,-0.03,-0.03,10084.44,B
11,11,2022-11-23 14:15:00-05:00,long,GOOGL,2763,102,98.11,10007.53,2784,98.29,10025.99,18.46,0.18,0.18,10102.91,B
12,12,2022-11-30 09:55:00-05:00,long,GOOGL,2987,105,95.83,10062.57,3065,101.90,10699.82,637.25,6.33,6.07,10740.15,B
13,13,2022-12-01 12:50:00-05:00,long,GOOGL,3100,106,101.31,10739.28,3133,101.44,10753.06,13.78,0.13,0.13,10753.93,B
14,14,2022-12-20 10:35:00-05:00,long,GOOGL,4087,121,88.78,10742.74,4090,88.81,10746.37,3.63,0.03,0.03,10757.56,B
15,15,2022-12-20 10:55:00-05:00,long,GOOGL,4091,121,88.63,10724.71,4092,88.78,10742.74,18.03,0.17,0.15,10775.59,B
16,16,2022-12-20 11:05:00-05:00,long,GOOGL,4093,121,88.75,10739.23,4094,88.30,10684.66,-54.57,-0.51,-0.45,10721.02,B
17,17,2022-12-20 12:55:00-05:00,long,GOOGL,4115,120,88.80,10656.48,4152,88.45,10614.48,-42.00,-0.39,-0.35,10679.02,B
18,18,2022-12-21 10:20:00-05:00,long,GOOGL,4162,119,89.06,10598.50,4219,89.77,10683.11,84.61,0.80,0.71,10763.63,B
19,19,2022-12-23 10:15:00-05:00,long,GOOGL,4317,120,88.96,10675.68,4375,89.32,10718.76,43.08,0.40,0.36,10806.71,B
20,20,2022-12-23 15:10:00-05:00,long,GOOGL,4376,120,89.31,10717.56,4377,89.35,10722.36,4.80,0.04,0.04,10811.51,B
21,21,2022-12-29 14:15:00-05:00,long,GOOGL,4599,121,88.67,10729.55,4615,88.81,10746.37,16.82,0.16,0.14,10828.33,B
22,22,2022-12-29 15:40:00-05:00,long,GOOGL,4616,122,88.74,10826.65,4617,88.75,10827.99,1.34,0.01,0.01,10829.67,B
23,23,2023-01-03 13:40:00-05:00,long,GOOGL,4748,121,88.97,10765.85,4776,88.98,10767.06,1.21,0.01,0.01,10830.88,B
24,24,2023-01-11 13:00:00-05:00,long,GOOGL,5208,119,90.87,10814.01,5244,91.10,10841.26,27.25,0.25,0.23,10858.13,B
25,25,2023-01-13 12:05:00-05:00,long,GOOGL,5353,119,90.88,10815.20,5400,91.24,10857.92,42.72,0.40,0.36,10900.85,B
26,26,2023-01-19 12:15:00-05:00,long,GOOGL,5589,117,92.85,10863.92,5762,99.89,11687.60,823.68,7.58,7.04,11724.53,B
27,27,2023-01-26 13:35:00-05:00,long,GOOGL,5995,120,97.04,11645.16,6096,99.99,11999.16,354.00,3.04,2.95,12078.53,B
28,28,2023-01-31 09:45:00-05:00,long,GOOGL,6183,123,97.54,11997.79,6258,98.78,12150.43,152.64,1.27,1.24,12231.17,B
29,29,2023-02-07 09:40:00-05:00,long,GOOGL,6572,117,103.88,12154.43,6611,106.39,12448.10,293.67,2.42,2.51,12524.84,B
30,30,2023-02-13 09:50:00-05:00,long,GOOGL,6886,132,94.75,12507.40,6887,95.04,12545.68,38.28,0.31,0.29,12563.12,B
31,31,2023-02-13 10:00:00-05:00,long,GOOGL,6888,132,94.89,12525.88,6889,94.52,12477.17,-48.71,-0.39,-0.37,12514.42,B
32,32,2023-02-13 12:25:00-05:00,long,GOOGL,6917,132,94.43,12465.16,6936,94.77,12510.17,45.01,0.36,0.34,12559.43,B
33,33,2023-02-13 14:05:00-05:00,long,GOOGL,6937,132,94.65,12494.33,6938,94.57,12483.64,-10.69,-0.09,-0.08,12548.74,B
34,34,2023-02-13 15:45:00-05:00,long,GOOGL,6957,132,94.56,12482.45,6960,94.05,12415.13,-67.32,-0.54,-0.51,12481.42,B
35,35,2023-02-15 10:30:00-05:00,long,GOOGL,7050,131,95.19,12470.41,7116,95.15,12465.04,-5.37,-0.04,-0.04,12476.04,B
36,36,2023-02-27 09:35:00-05:00,long,GOOGL,7585,139,89.75,12475.81,7610,89.73,12472.89,-2.92,-0.02,-0.02,12473.13,B
37,37,2023-02-27 12:00:00-05:00,long,GOOGL,7614,138,89.79,12391.43,7642,89.81,12394.19,2.76,0.02,0.02,12475.89,B
38,38,2023-03-01 09:55:00-05:00,long,GOOGL,7745,137,90.75,12433.30,7754,90.62,12415.49,-17.81,-0.14,-0.13,12458.08,B
39,39,2023-03-01 10:50:00-05:00,long,GOOGL,7756,137,90.47,12394.80,7757,90.38,12382.47,-12.33,-0.10,-0.09,12445.75,B
40,40,2023-03-01 15:55:00-05:00,long,GOOGL,7817,137,90.40,12385.35,7818,90.03,12334.66,-50.69,-0.41,-0.37,12395.06,B
41,41,2023-03-02 11:15:00-05:00,long,GOOGL,7839,137,90.32,12374.25,7840,90.26,12366.17,-8.08,-0.07,-0.06,12386.97,B
42,42,2023-03-02 12:10:00-05:00,long,GOOGL,7850,137,90.22,12360.69,8011,95.53,13088.16,727.47,5.89,5.31,13114.44,B
43,43,2023-03-06 14:25:00-05:00,long,GOOGL,8033,137,95.37,13066.10,8034,95.38,13067.47,1.37,0.01,0.01,13115.81,B
44,44,2023-03-16 14:25:00-04:00,long,GOOGL,8657,130,100.70,13091.39,8671,100.77,13100.62,9.23,0.07,0.07,13125.04,B
45,45,2023-03-21 09:30:00-04:00,long,GOOGL,8832,128,102.06,13064.19,8910,103.86,13294.46,230.27,1.76,1.80,13355.31,B
46,46,2023-03-29 09:30:00-04:00,long,GOOGL,9300,130,102.14,13278.59,9311,101.30,13169.52,-109.07,-0.82,-0.84,13246.24,B
47,47,2023-03-29 11:35:00-04:00,long,GOOGL,9325,130,101.45,13188.89,9342,101.19,13155.22,-33.67,-0.26,-0.26,13212.58,B
48,48,2023-03-29 14:55:00-04:00,long,GOOGL,9365,130,101.36,13177.19,9378,100.34,13044.72,-132.47,-1.01,-1.02,13080.10,B
49,49,2023-03-31 13:30:00-04:00,long,GOOGL,9504,127,102.60,13030.71,9534,103.05,13087.73,57.02,0.44,0.45,13137.13,B
50,50,2023-04-06 09:30:00-04:00,long,GOOGL,9768,125,104.54,13068.00,9846,107.48,13435.38,367.38,2.81,2.94,13504.50,B
51,51,2023-04-13 11:35:00-04:00,long,GOOGL,10105,126,106.72,13447.22,10164,108.07,13617.32,170.10,1.26,1.35,13674.60,B
52,52,2023-04-14 11:00:00-04:00,long,GOOGL,10176,126,107.75,13577.00,10193,107.79,13582.04,5.04,0.04,0.04,13679.64,B
53,53,2023-04-14 13:20:00-04:00,long,GOOGL,10204,126,107.95,13602.20,10205,107.85,13589.60,-12.60,-0.09,-0.10,13667.04,B
54,54,2023-04-14 14:00:00-04:00,long,GOOGL,10212,126,108.01,13609.64,10236,105.88,13341.26,-268.38,-1.97,-2.13,13398.66,B
55,55,2023-04-21 09:35:00-04:00,long,GOOGL,10549,126,105.89,13342.52,10550,105.76,13326.26,-16.25,-0.12,-0.13,13382.41,B
56,56,2023-04-21 09:45:00-04:00,long,GOOGL,10551,126,105.49,13292.24,10552,105.28,13265.78,-26.46,-0.20,-0.21,13355.95,B
57,57,2023-04-21 11:30:00-04:00,long,GOOGL,10572,126,105.61,13307.36,10577,105.35,13274.48,-32.89,-0.25,-0.26,13323.06,B
58,58,2023-04-21 13:50:00-04:00,long,GOOGL,10600,126,105.43,13284.68,10608,105.30,13268.18,-16.51,-0.12,-0.13,13306.56,B
59,59,2023-04-24 09:35:00-04:00,long,GOOGL,10627,125,106.09,13261.62,10638,105.99,13249.25,-12.38,-0.09,-0.10,13294.18,B
60,60,2023-04-24 12:50:00-04:00,long,GOOGL,10666,125,105.70,13213.00,10697,106.17,13271.62,58.62,0.44,0.47,13352.81,B
61,61,2023-04-27 14:25:00-04:00,long,GOOGL,10919,123,108.17,13305.40,10930,108.17,13305.28,-0.12,0.00,0.00,13352.68,B
62,62,2023-04-27 15:35:00-04:00,long,GOOGL,10933,123,108.12,13299.25,10934,107.86,13267.27,-31.98,-0.24,-0.26,13320.70,B
63,63,2023-05-01 11:05:00-04:00,long,GOOGL,11035,123,107.49,13221.64,11036,107.35,13204.42,-17.22,-0.13,-0.14,13303.48,B
64,64,2023-05-01 12:05:00-04:00,long,GOOGL,11047,123,107.36,13205.77,11072,107.87,13268.38,62.61,0.47,0.51,13366.09,B
65,65,2023-05-05 10:25:00-04:00,long,GOOGL,11339,127,104.76,13304.90,11352,104.88,13320.27,15.37,0.12,0.12,13381.46,B
66,66,2023-05-05 12:45:00-04:00,long,GOOGL,11367,127,105.08,13345.54,11501,108.91,13831.95,486.41,3.64,3.83,13867.87,B
67,67,2023-05-10 12:25:00-04:00,long,GOOGL,11597,127,108.80,13818.11,11685,116.97,14855.57,1037.46,7.51,8.17,14905.33,B
68,68,2023-05-11 14:55:00-04:00,long,GOOGL,11705,127,117.14,14877.29,11708,117.21,14886.05,8.76,0.06,0.07,14914.09,B
69,69,2023-05-11 15:15:00-04:00,long,GOOGL,11709,127,117.10,14872.08,11710,117.22,14887.45,15.37,0.10,0.12,14929.46,B
70,70,2023-05-11 15:25:00-04:00,long,GOOGL,11711,127,117.19,14883.64,11712,116.96,14854.43,-29.21,-0.20,-0.23,14900.25,B
71,71,2023-05-12 09:45:00-04:00,long,GOOGL,11721,127,116.79,14832.84,11722,116.75,14827.63,-5.21,-0.04,-0.04,14895.04,B
72,72,2023-05-12 09:55:00-04:00,long,GOOGL,11723,127,116.72,14823.82,11761,117.16,14879.83,56.01,0.38,0.44,14951.05,B
73,73,2023-05-12 15:05:00-04:00,long,GOOGL,11785,127,117.00,14859.38,11798,118.22,15014.45,155.07,1.04,1.22,15106.12,B
74,74,2023-05-17 11:45:00-04:00,long,GOOGL,11979,126,119.42,15047.30,11980,119.28,15029.78,-17.51,-0.12,-0.14,15088.60,B
75,75,2023-05-17 12:35:00-04:00,long,GOOGL,11989,125,119.82,14978.00,12021,121.27,15159.25,181.25,1.21,1.45,15269.85,B
76,76,2023-05-18 09:45:00-04:00,long,GOOGL,12033,126,121.02,15248.90,12084,122.14,15390.02,141.12,0.93,1.12,15410.97,B
77,77,2023-05-18 15:30:00-04:00,long,GOOGL,12102,125,122.85,15356.75,12129,123.94,15492.88,136.12,0.89,1.09,15547.10,B
78,78,2023-05-22 13:00:00-04:00,long,GOOGL,12228,124,125.16,15520.34,12246,125.39,15548.86,28.52,0.18,0.23,15575.62,B
79,79,2023-05-26 10:05:00-04:00,long,GOOGL,12505,125,123.96,15495.38,12545,124.66,15583.00,87.62,0.57,0.70,15663.24,B
80,80,2023-05-26 15:35:00-04:00,long,GOOGL,12571,125,124.73,15591.62,12576,123.92,15490.38,-101.25,-0.65,-0.81,15561.99,B
81,81,2023-05-31 12:00:00-04:00,long,GOOGL,12684,126,123.46,15556.34,12685,123.30,15536.18,-20.16,-0.13,-0.16,15541.83,B
82,82,2023-05-31 12:10:00-04:00,long,GOOGL,12686,126,123.32,15538.70,12687,123.14,15516.02,-22.68,-0.15,-0.18,15519.15,B
83,83,2023-05-31 13:40:00-04:00,long,GOOGL,12704,125,123.46,15433.00,12710,123.34,15417.88,-15.12,-0.10,-0.12,15504.03,B
84,84,2023-05-31 15:35:00-04:00,long,GOOGL,12727,125,123.42,15427.88,12728,123.51,15439.12,11.25,0.07,0.09,15515.28,B
85,85,2023-05-31 15:45:00-04:00,long,GOOGL,12729,125,123.71,15464.25,12730,122.76,15345.50,-118.75,-0.77,-0.95,15396.53,B
86,86,2023-06-01 09:45:00-04:00,long,GOOGL,12735,123,124.32,15291.73,12747,123.76,15222.97,-68.76,-0.45,-0.56,15327.77,B
87,87,2023-06-01 12:25:00-04:00,long,GOOGL,12767,124,123.21,15278.54,12768,123.19,15276.06,-2.48,-0.02,-0.02,15325.29,B
88,88,2023-06-01 12:50:00-04:00,long,GOOGL,12772,124,123.25,15283.37,12773,123.09,15263.66,-19.72,-0.13,-0.16,15305.58,B
89,89,2023-06-01 13:45:00-04:00,long,GOOGL,12783,124,123.34,15294.66,12798,123.47,15310.78,16.12,0.11,0.13,15321.70,B
90,90,2023-06-01 15:05:00-04:00,long,GOOGL,12799,124,123.47,15310.65,12800,123.50,15314.50,3.84,0.03,0.03,15325.54,B
91,91,2023-06-01 15:15:00-04:00,long,GOOGL,12801,124,123.44,15306.93,12802,123.25,15283.50,-23.44,-0.15,-0.19,15302.10,B
92,92,2023-06-02 12:35:00-04:00,long,GOOGL,12847,122,124.87,15234.63,12864,124.91,15239.39,4.76,0.03,0.04,15306.86,B
93,93,2023-06-02 14:45:00-04:00,long,GOOGL,12873,122,125.05,15256.59,12879,125.07,15258.91,2.32,0.02,0.02,15309.18,B
94,94,2023-06-02 15:20:00-04:00,long,GOOGL,12880,122,125.02,15252.81,12881,125.01,15251.59,-1.22,-0.01,-0.01,15307.96,B
95,95,2023-06-06 10:00:00-04:00,long,GOOGL,12972,121,126.26,15277.94,13032,128.02,15490.90,212.96,1.39,1.76,15520.92,B
96,96,2023-06-12 11:30:00-04:00,long,GOOGL,13302,126,122.47,15431.60,13392,124.01,15625.64,194.04,1.26,1.54,15714.96,B
97,97,2023-06-15 10:10:00-04:00,long,GOOGL,13520,126,123.79,15597.92,13521,123.67,15582.80,-15.12,-0.10,-0.12,15699.84,B
98,98,2023-06-15 10:20:00-04:00,long,GOOGL,13522,126,123.62,15576.62,13523,123.58,15571.46,-5.17,-0.03,-0.04,15694.67,B
99,99,2023-06-15 11:00:00-04:00,long,GOOGL,13530,126,123.89,15610.64,13546,124.10,15637.10,26.46,0.17,0.21,15721.13,B
100,100,2023-06-22 10:10:00-04:00,long,GOOGL,13832,129,121.17,15631.45,13833,120.77,15579.85,-51.60,-0.33,-0.40,15669.53,B
101,101,2023-06-22 10:20:00-04:00,long,GOOGL,13834,129,120.67,15566.82,13835,120.72,15573.27,6.45,0.04,0.05,15675.98,B
102,102,2023-06-22 10:30:00-04:00,long,GOOGL,13836,129,120.64,15563.08,13837,120.44,15537.28,-25.80,-0.17,-0.20,15650.18,B
103,103,2023-06-22 11:15:00-04:00,long,GOOGL,13845,129,120.75,15577.14,13902,122.19,15762.90,185.76,1.19,1.44,15835.94,B
104,104,2023-06-28 14:15:00-04:00,long,GOOGL,14193,132,119.81,15815.32,14214,119.94,15832.48,17.16,0.11,0.13,15853.10,B
105,105,2023-06-30 11:20:00-04:00,long,GOOGL,14314,131,120.64,15804.23,14338,120.44,15778.16,-26.07,-0.16,-0.20,15827.04,B
106,106,2023-07-03 11:50:00-04:00,long,GOOGL,14398,132,119.44,15766.61,14476,122.20,16130.93,364.32,2.31,2.76,16191.36,B
107,107,2023-07-05 14:55:00-04:00,long,GOOGL,14477,132,122.11,16118.92,14478,122.09,16116.28,-2.64,-0.02,-0.02,16188.72,B
108,108,2023-07-11 10:25:00-04:00,long,GOOGL,14735,138,116.72,16107.91,14768,117.17,16170.01,62.10,0.39,0.45,16250.82,B
109,109,2023-07-11 15:55:00-04:00,long,GOOGL,14801,138,117.15,16167.25,14824,119.65,16512.11,344.86,2.13,2.50,16595.68,B
110,110,2023-07-12 13:35:00-04:00,long,GOOGL,14851,139,119.25,16576.17,14863,119.25,16576.17,0.00,0.00,0.00,16595.68,B
111,111,2023-07-13 14:20:00-04:00,long,GOOGL,14938,133,124.31,16533.76,14978,125.45,16685.25,151.49,0.92,1.14,16747.16,B
112,112,2023-07-14 14:15:00-04:00,long,GOOGL,15015,133,125.26,16660.11,15016,125.22,16654.66,-5.45,-0.03,-0.04,16741.71,B
113,113,2023-07-14 15:00:00-04:00,long,GOOGL,15024,133,125.18,16649.47,15037,126.64,16843.65,194.18,1.17,1.46,16935.89,B
114,114,2023-07-21 09:35:00-04:00,long,GOOGL,15349,141,119.49,16848.65,15379,119.69,16876.85,28.20,0.17,0.20,16964.09,B
115,115,2023-07-21 13:30:00-04:00,long,GOOGL,15396,141,120.11,16935.93,15408,119.87,16902.09,-33.84,-0.20,-0.24,16930.25,B
116,116,2023-07-21 14:40:00-04:00,long,GOOGL,15410,140,120.09,16813.16,15411,120.10,16814.56,1.40,0.01,0.01,16931.65,B
117,117,2023-07-21 14:50:00-04:00,long,GOOGL,15412,141,119.99,16919.15,15413,119.86,16900.68,-18.47,-0.11,-0.13,16913.18,B
118,118,2023-07-24 13:50:00-04:00,long,GOOGL,15478,138,121.88,16819.99,15479,121.69,16793.77,-26.22,-0.16,-0.19,16886.96,B
119,119,2023-07-25 09:55:00-04:00,long,GOOGL,15509,137,122.37,16765.24,15510,121.74,16678.93,-86.31,-0.51,-0.63,16800.65,B
120,120,2023-07-25 12:10:00-04:00,long,GOOGL,15536,138,121.58,16778.45,15575,122.95,16967.51,189.06,1.13,1.37,16989.71,B
121,121,2023-07-25 15:30:00-04:00,long,GOOGL,15576,138,122.81,16948.19,15577,122.72,16935.77,-12.42,-0.07,-0.09,16977.29,B
122,122,2023-07-26 12:35:00-04:00,long,GOOGL,15619,131,129.38,16949.30,15626,129.50,16964.89,15.59,0.09,0.12,16992.88,B
123,123,2023-07-26 14:10:00-04:00,long,GOOGL,15638,131,129.43,16955.72,15646,130.13,17047.55,91.83,0.54,0.70,17084.71,B
124,124,2023-07-26 14:55:00-04:00,long,GOOGL,15647,131,129.84,17009.56,15648,129.85,17010.74,1.18,0.01,0.01,17085.89,B
125,125,2023-08-03 11:10:00-04:00,long,GOOGL,16070,132,128.71,16990.12,16100,128.95,17021.93,31.81,0.19,0.24,17117.70,B
126,126,2023-08-07 15:10:00-04:00,long,GOOGL,16274,130,131.32,17072.12,16284,130.70,16991.52,-80.60,-0.47,-0.62,17037.10,B
127,127,2023-08-14 09:55:00-04:00,long,GOOGL,16601,131,129.97,17026.59,16639,131.08,17172.00,145.41,0.85,1.11,17182.51,B
128,128,2023-08-14 15:25:00-04:00,long,GOOGL,16667,131,130.75,17128.64,16674,131.13,17178.55,49.91,0.29,0.38,17232.42,B
129,129,2023-08-23 12:45:00-04:00,long,GOOGL,17181,130,132.46,17220.19,17212,133.06,17298.32,78.13,0.45,0.60,17310.55,B
130,130,2023-08-23 15:25:00-04:00,long,GOOGL,17213,130,133.04,17295.72,17214,132.96,17285.32,-10.40,-0.06,-0.08,17300.15,B
131,131,2023-08-23 15:35:00-04:00,long,GOOGL,17215,130,133.04,17295.59,17216,132.88,17274.92,-20.67,-0.12,-0.16,17279.48,B
132,132,2023-08-30 10:05:00-04:00,long,GOOGL,17539,127,135.72,17236.82,17564,135.43,17199.99,-36.83,-0.21,-0.29,17242.65,B
133,133,2023-08-30 12:15:00-04:00,long,GOOGL,17565,127,135.42,17198.85,17566,135.27,17179.67,-19.18,-0.11,-0.15,17223.48,B
134,134,2023-08-30 13:25:00-04:00,long,GOOGL,17579,127,135.31,17184.88,17580,135.36,17191.10,6.22,0.04,0.05,17229.70,B
135,135,2023-08-30 13:35:00-04:00,long,GOOGL,17581,127,135.36,17191.10,17637,136.67,17357.60,166.50,0.97,1.31,17396.20,B
136,136,2023-09-08 09:45:00-04:00,long,GOOGL,18003,128,135.71,17371.26,18060,136.35,17453.18,81.92,0.47,0.64,17478.12,B
137,137,2023-09-11 09:35:00-04:00,long,GOOGL,18079,127,136.90,17386.68,18084,136.90,17386.81,0.13,0.00,0.00,17478.24,B
138,138,2023-09-11 12:40:00-04:00,long,GOOGL,18116,128,136.47,17468.54,18156,136.26,17441.79,-26.75,-0.15,-0.21,17451.49,B
139,139,2023-09-14 09:30:00-04:00,long,GOOGL,18312,127,136.88,17384.14,18313,137.12,17414.75,30.61,0.18,0.24,17482.10,B
140,140,2023-09-14 09:40:00-04:00,long,GOOGL,18314,127,137.53,17466.69,18315,137.29,17436.34,-30.35,-0.17,-0.24,17451.74,B
141,141,2023-09-14 10:35:00-04:00,long,GOOGL,18325,127,137.32,17440.02,18379,138.43,17581.12,141.10,0.81,1.11,17592.84,B
142,142,2023-09-14 15:10:00-04:00,long,GOOGL,18380,126,138.53,17455.16,18381,138.32,17428.82,-26.33,-0.15,-0.21,17566.51,B
143,143,2023-09-18 09:30:00-04:00,long,GOOGL,18468,127,138.10,17539.21,18496,138.72,17617.95,78.74,0.45,0.62,17645.25,B
144,144,2023-09-18 11:55:00-04:00,long,GOOGL,18497,127,138.59,17601.44,18498,138.50,17589.88,-11.56,-0.07,-0.09,17633.69,B
145,145,2023-09-18 14:15:00-04:00,long,GOOGL,18525,127,138.33,17568.42,18539,138.48,17587.34,18.92,0.11,0.15,17652.61,B
146,146,2023-09-25 11:20:00-04:00,long,GOOGL,18880,135,130.62,17634.10,18919,130.89,17670.56,36.45,0.21,0.27,17689.06,B
147,147,2023-09-25 14:40:00-04:00,long,GOOGL,18920,135,130.77,17654.49,18921,130.76,17653.14,-1.35,-0.01,-0.01,17687.71,B
148,148,2023-09-25 14:50:00-04:00,long,GOOGL,18922,135,130.72,17647.74,18923,130.59,17630.19,-17.55,-0.10,-0.13,17670.16,B
149,149,2023-09-25 15:40:00-04:00,long,GOOGL,18932,135,130.82,17661.10,18936,129.45,17476.29,-184.81,-1.05,-1.37,17485.35,B
150,150,2023-09-27 09:30:00-04:00,long,GOOGL,19014,135,129.47,17478.86,19058,129.51,17484.39,5.53,0.03,0.04,17490.88,B
151,151,2023-09-27 13:15:00-04:00,long,GOOGL,19059,134,129.58,17364.26,19060,129.56,17361.58,-2.68,-0.02,-0.02,17488.20,B
152,152,2023-09-28 10:15:00-04:00,long,GOOGL,19101,133,130.91,17411.43,19142,132.31,17597.76,186.33,1.07,1.40,17674.54,B
153,153,2023-09-28 15:15:00-04:00,long,GOOGL,19161,133,132.62,17638.86,19162,132.67,17645.51,6.65,0.04,0.05,17681.19,B
154,154,2023-09-28 15:25:00-04:00,long,GOOGL,19163,133,132.73,17653.49,19164,132.54,17628.35,-25.14,-0.14,-0.19,17656.05,B
155,155,2023-10-02 14:20:00-04:00,long,GOOGL,19306,132,133.22,17585.57,19307,132.95,17549.93,-35.64,-0.20,-0.27,17620.41,B
156,156,2023-10-02 15:35:00-04:00,long,GOOGL,19321,131,133.79,17527.01,19326,133.45,17482.34,-44.67,-0.25,-0.34,17575.74,B
157,157,2023-10-04 15:10:00-04:00,long,GOOGL,19472,130,135.01,17551.69,19482,135.01,17551.69,0.00,0.00,0.00,17575.74,B
158,158,2023-10-06 09:45:00-04:00,long,GOOGL,19563,129,135.59,17491.63,19634,137.96,17797.36,305.73,1.75,2.37,17881.47,B
159,159,2023-10-06 15:45:00-04:00,long,GOOGL,19635,129,137.96,17797.36,19636,137.64,17755.95,-41.41,-0.23,-0.32,17840.06,B
160,160,2023-10-09 11:30:00-04:00,long,GOOGL,19662,129,137.79,17775.30,19714,138.41,17855.41,80.11,0.45,0.62,17920.17,B
161,161,2023-10-11 14:10:00-04:00,long,GOOGL,19850,127,140.02,17783.05,19889,140.70,17869.41,86.36,0.49,0.68,18006.53,B
162,162,2023-10-16 12:40:00-04:00,long,GOOGL,20066,129,138.73,17896.56,20102,139.28,17967.64,71.08,0.40,0.55,18077.61,B
163,163,2023-10-30 12:00:00-04:00,long,GOOGL,20838,145,124.64,18073.38,20878,125.20,18154.44,81.06,0.45,0.56,18158.66,B
164,164,2023-10-30 15:25:00-04:00,long,GOOGL,20879,145,124.98,18122.68,20880,124.93,18115.28,-7.40,-0.04,-0.05,18151.27,B
165,165,2023-10-30 15:35:00-04:00,long,GOOGL,20881,145,124.89,18109.48,20882,124.66,18076.28,-33.21,-0.18,-0.23,18118.06,B
166,166,2023-11-01 14:05:00-04:00,long,GOOGL,21019,144,125.28,18040.75,21071,127.45,18353.38,312.62,1.73,2.17,18430.69,B

In [2]:
import sqlite3 as sq3
import pandas as pd

con = sq3.connect('long_backtest_data.sql')
df = pd.read_sql_query("SELECT * FROM data LIMIT 10", con)
print(df)
con.close()

   index                   datetime direction symbol  buy_index  units  \
0      0  2022-10-06 12:50:00-04:00      long  GOOGL        118     97
1      1  2022-10-17 12:05:00-04:00      long  GOOGL        655     99
2      2  2022-10-18 11:45:00-04:00      long  GOOGL        705     99
3      3  2022-10-18 15:50:00-04:00      long  GOOGL        754     99
4      4  2022-10-25 11:55:00-04:00      long  GOOGL       1097     96
5      5  2022-10-25 14:15:00-04:00      long  GOOGL       1125     96
6      6  2022-11-04 12:40:00-04:00      long  GOOGL       1730    108
7      7  2022-11-07 13:15:00-05:00      long  GOOGL       1815    108
8      8  2022-11-10 14:00:00-05:00      long  GOOGL       2058    104
9      9  2022-11-16 10:45:00-05:00      long  GOOGL       2331    101

   buying_price  entry_amount  sell_index  sell_price  exit_amount  \
0        102.20       9913.69         120      102.07      9901.18
1        100.24       9924.06         688      100.39      9938.91
2        100.64       9963.66         733      100.80      9979.50
3        100.63       9962.77         756      100.58      9957.72
4        103.82       9967.01        1102      103.83      9968.06
5        103.64       9949.82        1146       95.79      9196.22
6         85.09       9190.15        1795       87.74      9476.35
7         87.89       9492.55        1886       89.56      9672.91
8         93.52       9726.39        2154       96.49     10035.27
9         98.49       9947.79        2371       99.00      9999.30

   gain_or_loss  performance  move   balance
0        -12.51        -0.13 -0.13   9987.49
1         14.85         0.15  0.15  10002.34
2         15.84         0.16  0.16  10018.18
3         -5.05        -0.05 -0.05  10013.13
4          1.06         0.01  0.01  10014.18
5       -753.60        -7.57 -7.85   9260.58
6        286.20         3.11  2.65   9546.78
7        180.36         1.90  1.67   9727.14
8        308.88         3.18  2.97  10036.02
9         51.51         0.52  0.51  10087.53

In [104]:
import sqlite3 as sq3
import pandas as pd

con = sq3.connect('trading_vow.sql')
df = pd.read_sql_query("SELECT * FROM data", con)
con.close()

#result = df[df["symbol"]== 'GOOGL']
pd.set_option('display.max_rows', None)
display(df)

     index        Date             Time  Candle Symbol  Quantity   Price Side
0        0  2022-10-17  11:35:00.000000     649    AMD       172   58.03    B
1        1  2022-10-17  14:10:00.000000     680    AMD       172   58.06    S
2        2  2022-10-25  14:15:00.000000    1125    AMD       162   61.72    B
3        3  2022-10-25  15:35:00.000000    1141    AMD       162   61.65    S
4        4  2022-10-28  15:25:00.000000    1373    AMD       161   61.89    B
5        5  2022-10-31  09:30:00.000000    1380    AMD       161   61.36    S
6        6  2022-11-01  12:00:00.000000    1488    AMD       164   60.41    B
7        7  2022-11-01  13:10:00.000000    1502    AMD       164   60.36    S
8        8  2022-11-07  10:15:00.000000    1779    AMD       158   62.46    B
9        9  2022-11-07  10:20:00.000000    1780    AMD       158   62.07    S
10      10  2022-11-07  11:35:00.000000    1795    AMD       157   62.37    B
11      11  2022-11-08  13:05:00.000000    1843    AMD       157   64.52    S
12      12  2022-11-17  10:30:00.000000    2214    AMD       138   73.28    B
13      13  2022-11-18  09:30:00.000000    2244    AMD       138   74.19    S
14      14  2022-11-22  09:55:00.000000    2345    AMD       140   73.20    B
15      15  2022-11-23  11:25:00.000000    2435    AMD       140   76.49    S
16      16  2022-11-29  11:40:00.000000    2552    AMD       146   73.33    B
17      17  2022-11-29  14:40:00.000000    2588    AMD       146   73.55    S
18      18  2022-12-07  11:00:00.000000    2886    AMD       152   70.83    B
19      19  2022-12-07  11:05:00.000000    2887    AMD       152   70.73    S
20      20  2022-12-07  11:10:00.000000    2888    AMD       152   70.54    B
21      21  2022-12-07  12:55:00.000000    2909    AMD       152   70.79    S
22      22  2022-12-08  10:15:00.000000    2931    AMD       154   70.23    B
23      23  2022-12-08  11:40:00.000000    2948    AMD       154   70.48    S
24      24  2022-12-08  11:45:00.000000    2949    AMD       153   70.63    B
25      25  2022-12-08  11:50:00.000000    2950    AMD       153   70.66    S
26      26  2022-12-08  11:55:00.000000    2951    AMD       154   70.48    B
27      27  2022-12-08  12:00:00.000000    2952    AMD       154   70.30    S
28      28  2022-12-08  15:15:00.000000    2991    AMD       154   70.08    B
29      29  2022-12-09  12:00:00.000000    3000    AMD       154   70.46    S
30      30  2022-12-12  10:40:00.000000    3062    AMD       158   68.73    B
31      31  2022-12-12  13:30:00.000000    3096    AMD       158   69.71    S
32      32  2022-12-12  14:55:00.000000    3113    AMD       157   70.13    B
33      33  2022-12-13  11:30:00.000000    3144    AMD       157   72.93    S
34      34  2022-12-20  10:05:00.000000    3433    AMD       176   65.01    B
35      35  2022-12-20  11:45:00.000000    3453    AMD       176   65.23    S
36      36  2022-12-20  13:10:00.000000    3470    AMD       176   65.24    B
37      37  2022-12-20  15:15:00.000000    3495    AMD       176   65.52    S
38      38  2022-12-23  10:30:00.000000    3606    AMD       179   64.46    B
39      39  2022-12-23  10:35:00.000000    3607    AMD       179   64.61    S
40      40  2022-12-23  12:25:00.000000    3629    AMD       180   64.12    B
41      41  2022-12-27  09:30:00.000000    3648    AMD       180   63.96    S
42      42  2022-12-29  14:35:00.000000    3799    AMD       178   64.86    B
43      43  2022-12-30  09:30:00.000000    3816    AMD       178   64.11    S
44      44  2023-01-03  11:00:00.000000    3906    AMD       176   64.87    B
45      45  2023-01-03  11:05:00.000000    3907    AMD       176   64.48    S
46      46  2023-01-10  11:05:00.000000    4195    AMD       168   67.49    B
47      47  2023-01-10  11:10:00.000000    4196    AMD       168   67.62    S
48      48  2023-01-10  11:15:00.000000    4197    AMD       168   67.43    B
49      49  2023-01-10  11:20:00.000000    4198    AMD       168   67.63    S
50      50  2023-01-10  11:25:00.000000    4199    AMD       169   67.51    B
51      51  2023-01-11  09:40:00.000000    4256    AMD       169   68.26    S
52      52  2023-01-11  09:50:00.000000    4258    AMD       168   68.46    B
53      53  2023-01-11  09:55:00.000000    4259    AMD       168   68.09    S
54      54  2023-01-11  12:10:00.000000    4286    AMD       168   68.21    B
55      55  2023-01-13  10:40:00.000000    4328    AMD       168   70.60    S
56      56  2023-01-17  12:30:00.000000    4392    AMD       165   71.63    B
57      57  2023-01-17  14:25:00.000000    4415    AMD       165   71.90    S
58      58  2023-01-20  09:55:00.000000    4595    AMD       175   68.17    B
59      59  2023-01-23  13:40:00.000000    4688    AMD       175   75.94    S
60      60  2023-01-31  09:50:00.000000    4996    AMD       181   73.22    B
61      61  2023-01-31  12:40:00.000000    5030    AMD       181   74.37    S
62      62  2023-02-07  11:45:00.000000    5247    AMD       161   83.75    B
63      63  2023-02-07  13:05:00.000000    5263    AMD       161   84.50    S
64      64  2023-02-14  15:55:00.000000    5513    AMD       158   85.94    B
65      65  2023-02-15  09:30:00.000000    5514    AMD       158   85.34    S
66      66  2023-02-27  11:50:00.000000    5902    AMD       170   79.48    B
67      67  2023-02-27  14:05:00.000000    5929    AMD       170   79.34    S
68      68  2023-02-27  14:10:00.000000    5930    AMD       169   79.44    B
69      69  2023-02-27  14:15:00.000000    5931    AMD       169   79.22    S
70      70  2023-03-08  14:20:00.000000    6310    AMD       158   85.01    B
71      71  2023-03-09  12:10:00.000000    6362    AMD       158   86.72    S
72      72  2023-03-29  11:45:00.000000    7131    AMD       143   95.84    B
73      73  2023-03-29  13:25:00.000000    7151    AMD       143   96.17    S
74      74  2023-03-29  13:30:00.000000    7152    AMD       143   95.86    B
75      75  2023-03-29  13:35:00.000000    7153    AMD       143   95.61    S
76      76  2023-03-29  14:40:00.000000    7166    AMD       143   95.88    B
77      77  2023-03-30  12:30:00.000000    7218    AMD       143   98.55    S
78      78  2023-04-10  14:30:00.000000    7578    AMD       147   95.56    B
79      79  2023-04-11  09:30:00.000000    7596    AMD       147   95.08    S
80      80  2023-04-14  09:55:00.000000    7733    AMD       151   92.76    B
81      81  2023-04-17  09:30:00.000000    7734    AMD       151   89.91    S
82      82  2023-04-19  11:15:00.000000    7911    AMD       152   89.66    B
83      83  2023-04-19  11:20:00.000000    7912    AMD       152   89.66    S
84      84  2023-04-19  12:25:00.000000    7925    AMD       151   89.71    B
85      85  2023-04-19  14:25:00.000000    7949    AMD       151   90.01    S
86      86  2023-04-28  10:20:00.000000    8272    AMD       155   87.81    B
87      87  2023-04-28  10:30:00.000000    8274    AMD       155   87.75    S
88      88  2023-04-28  10:35:00.000000    8275    AMD       156   87.56    B
89      89  2023-04-28  10:40:00.000000    8276    AMD       156   87.60    S
90      90  2023-04-28  10:45:00.000000    8277    AMD       155   87.75    B
91      91  2023-04-28  10:50:00.000000    8278    AMD       155   87.66    S
92      92  2023-04-28  15:00:00.000000    8328    AMD       152   89.47    B
93      93  2023-05-01  09:55:00.000000    8345    AMD       152   89.51    S
94      94  2023-05-01  11:55:00.000000    8369    AMD       152   89.73    B
95      95  2023-05-01  13:30:00.000000    8388    AMD       152   90.16    S
96      96  2023-05-01  13:35:00.000000    8389    AMD       152   90.04    B
97      97  2023-05-01  13:40:00.000000    8390    AMD       152   89.96    S
98      98  2023-05-01  13:45:00.000000    8391    AMD       152   89.90    B
99      99  2023-05-01  13:50:00.000000    8392    AMD       152   89.87    S
100    100  2023-05-04  09:50:00.000000    8476    AMD       165   83.10    B
101    101  2023-05-04  09:55:00.000000    8477    AMD       165   82.94    S
102    102  2023-05-04  10:00:00.000000    8478    AMD       164   82.96    B
103    103  2023-05-04  10:05:00.000000    8479    AMD       164   83.12    S
104    104  2023-05-04  10:10:00.000000    8480    AMD       165   82.65    B
105    105  2023-05-08  09:30:00.000000    8526    AMD       165   89.92    S
106    106  2023-05-08  10:25:00.000000    8537    AMD       165   90.33    B
107    107  2023-05-09  09:30:00.000000    8604    AMD       165   94.34    S
108    108  2023-05-17  11:55:00.000000    8927    AMD       151  102.65    B
109    109  2023-05-18  12:05:00.000000    9007    AMD       151  106.51    S
110    110  2023-05-18  13:40:00.000000    9026    AMD       151  106.67    B
111    111  2023-05-19  09:30:00.000000    9054    AMD       151  105.97    S
112    112  2023-05-26  14:10:00.000000    9308    AMD       127  126.28    B
113    113  2023-05-30  09:30:00.000000    9330    AMD       127  128.49    S
114    114  2023-06-06  14:40:00.000000    9656    AMD       132  122.83    B
115    115  2023-06-07  09:35:00.000000    9673    AMD       132  123.85    S
116    116  2023-06-27  10:30:00.000000   10398    AMD       152  107.88    B
117    117  2023-06-28  09:30:00.000000   10464    AMD       152  108.25    S
118    118  2023-06-30  11:30:00.000000   10644    AMD       144  113.97    B
119    119  2023-07-05  10:20:00.000000   10660    AMD       144  116.23    S
120    120  2023-07-12  15:40:00.000000   11012    AMD       146  114.65    B
121    121  2023-07-13  10:20:00.000000   11026    AMD       146  114.66    S
122    122  2023-07-13  11:00:00.000000   11034    AMD       146  114.86    B
123    123  2023-07-13  11:05:00.000000   11035    AMD       146  114.86    S
124    124  2023-07-25  11:40:00.000000   11396    AMD       149  112.65    B
125    125  2023-07-25  15:45:00.000000   11445    AMD       149  113.57    S
126    126  2023-08-14  09:55:00.000000   12131    AMD       156  108.73    B
127    127  2023-08-15  09:30:00.000000   12204    AMD       156  113.06    S
128    128  2023-08-29  09:30:00.000000   12852    AMD       171  103.09    B
129    129  2023-08-29  13:50:00.000000   12904    AMD       171  106.28    S
130    130  2023-08-29  13:55:00.000000   12905    AMD       171  106.16    B
131    131  2023-08-31  11:30:00.000000   12930    AMD       171  106.39    S
132    132  2023-09-12  14:50:00.000000   13270    AMD       172  105.82    B
133    133  2023-09-12  14:55:00.000000   13271    AMD       172  105.76    S
134    134  2023-10-04  09:35:00.000000   14088    AMD       180  100.87    B
135    135  2023-10-04  13:20:00.000000   14133    AMD       180  102.19    S
136    136  2023-10-04  14:40:00.000000   14149    AMD       179  102.87    B
137    137  2023-10-05  09:30:00.000000   14165    AMD       179  102.94    S
138    138  2023-10-06  13:40:00.000000   14293    AMD       173  106.70    B
139    139  2023-10-10  13:20:00.000000   14343    AMD       173  108.61    S
140    140  2023-10-10  15:10:00.000000   14365    AMD       172  108.96    B
141    141  2023-10-11  09:35:00.000000   14376    AMD       172  109.69    S
142    142  2023-10-12  15:15:00.000000   14432    AMD       173  108.87    B
143    143  2023-10-13  09:30:00.000000   14441    AMD       173  107.53    S
144    144  2023-10-27  12:50:00.000000   15135    AMD       192   97.10    B
145    145  2023-10-27  13:30:00.000000   15143    AMD       192   96.81    S
146    146  2023-10-27  13:45:00.000000   15146    AMD       192   96.82    B
147    147  2023-10-27  13:50:00.000000   15147    AMD       192   96.59    S
148    148  2023-10-27  14:45:00.000000   15158    AMD       192   96.68    B
149    149  2023-10-27  14:50:00.000000   15159    AMD       192   96.67    S
150    150  2023-11-16  09:50:00.000000   15885    AMD       156  119.05    B
151    151  2023-11-16  13:55:00.000000   15934    AMD       156  119.89    S
152    152  2023-11-17  10:05:00.000000   15966    AMD       156  119.86    B
153    153  2023-11-17  10:10:00.000000   15967    AMD       156  119.97    S
154    154  2023-11-17  10:15:00.000000   15968    AMD       155  120.32    B
155    155  2023-11-17  10:20:00.000000   15969    AMD       155  119.91    S
156    156  2023-11-22  12:15:00.000000   16064    AMD       151  123.03    B
157    157  2023-11-22  13:55:00.000000   16084    AMD       151  123.51    S
158    158  2023-11-22  14:00:00.000000   16085    AMD       152  123.41    B
159    159  2023-11-22  14:05:00.000000   16086    AMD       152  123.32    S
160    160  2023-11-24  10:05:00.000000   16116    AMD       152  123.00    B
161    161  2023-11-24  10:10:00.000000   16117    AMD       152  122.86    S
162    162  2023-11-24  10:15:00.000000   16118    AMD       152  122.70    B
163    163  2023-11-24  10:20:00.000000   16119    AMD       152  122.65    S
164    164  2023-11-24  11:55:00.000000   16138    AMD       152  122.85    B
165    165  2023-11-27  09:35:00.000000   16140    AMD       152  123.54    S
166    166  2023-12-21  12:15:00.000000   17036    AMD       135  139.10    B
167    167  2023-12-21  13:30:00.000000   17051    AMD       135  139.11    S
168    168  2023-12-21  14:45:00.000000   17066    AMD       135  139.04    B
169    169  2023-12-22  10:40:00.000000   17095    AMD       135  140.15    S
170    170  2023-12-26  12:20:00.000000   17193    AMD       133  141.72    B
171    171  2023-12-26  12:50:00.000000   17199    AMD       133  141.70    S
172    172  2023-12-26  14:10:00.000000   17215    AMD       133  142.03    B
173    173  2023-12-27  10:40:00.000000   17251    AMD       133  144.10    S
174    174  2023-12-27  10:45:00.000000   17252    AMD       133  144.19    B
175    175  2023-12-27  10:50:00.000000   17253    AMD       133  143.83    S
176    176  2023-12-27  11:10:00.000000   17257    AMD       132  144.42    B
177    177  2023-12-29  10:25:00.000000   17314    AMD       132  150.75    S
178    178  2024-01-09  10:10:00.000000   17689    AMD       135  147.36    B
179    179  2024-01-11  09:30:00.000000   17747    AMD       135  149.16    S
180    180  2024-02-09  12:05:00.000000   18762    AMD       118  171.43    B
181    181  2024-02-12  13:10:00.000000   18853    AMD       118  176.57    S
182    182  2024-02-14  12:20:00.000000   18999    AMD       118  175.69    B
183    183  2024-02-15  09:30:00.000000   19043    AMD       118  178.15    S
184    184  2024-03-01  15:00:00.000000   19589    AMD       105  201.50    B
185    185  2024-03-04  12:10:00.000000   19633    AMD       105  209.31    S
186    186  2024-04-05  13:45:00.000000   21047    AMD       128  171.70    B
187    187  2024-04-05  13:50:00.000000   21048    AMD       128  171.29    S
188    188  2024-04-11  13:00:00.000000   21182    AMD       129  169.91    B
189    189  2024-04-11  14:40:00.000000   21202    AMD       129  170.00    S
190    190  2024-04-11  15:35:00.000000   21213    AMD       128  170.56    B
191    191  2024-04-12  09:30:00.000000   21218    AMD       128  163.64    S
192    192  2024-04-25  10:25:00.000000   21661    AMD       138  152.60    B
193    193  2024-04-29  15:00:00.000000   21746    AMD       138  158.98    S
194    194  2024-05-03  13:35:00.000000   22041    AMD       146  150.18    B
195    195  2024-05-07  12:35:00.000000   22083    AMD       146  155.50    S
196    196  2024-05-14  14:25:00.000000   22405    AMD       149  152.43    B
197    197  2024-05-17  12:40:00.000000   22516    AMD       149  164.80    S
198    198  2024-06-07  09:55:00.000000   23329    AMD       145  168.31    B
199    199  2024-06-10  09:30:00.000000   23330    AMD       145  162.00    S
200    200  2024-07-02  09:30:00.000000   24146    AMD       147  159.87    B
201    201  2024-07-02  09:50:00.000000   24150    AMD       147  159.01    S
202    202  2024-07-02  11:35:00.000000   24171    AMD       147  159.67    B
203    203  2024-07-03  09:30:00.000000   24224    AMD       147  165.27    S
204    204  2024-08-08  15:50:00.000000   25650    AMD       179  135.65    B
205    205  2024-08-09  09:30:00.000000   25652    AMD       179  134.81    S
206    206  2024-08-12  14:35:00.000000   25791    AMD       176  136.75    B
207    207  2024-08-12  14:55:00.000000   25795    AMD       176  136.86    S
208    208  2024-08-13  11:45:00.000000   25835    AMD       172  140.26    B
209    209  2024-08-14  09:30:00.000000   25862    AMD       172  140.93    S
210    210  2024-08-15  15:15:00.000000   25931    AMD       165  147.32    B
211    211  2024-08-19  12:15:00.000000   25979    AMD       165  152.31    S
212    212  2024-08-19  13:45:00.000000   25997    AMD       164  152.93    B
213    213  2024-08-20  11:10:00.000000   26044    AMD       164  157.25    S
214    214  2024-08-21  09:45:00.000000   26105    AMD       165  156.67    B
215    215  2024-08-21  10:40:00.000000   26116    AMD       165  157.67    S
216    216  2024-08-21  10:45:00.000000   26117    AMD       165  157.01    B
217    217  2024-08-21  11:25:00.000000   26125    AMD       165  157.11    S
218    218  2024-08-21  11:50:00.000000   26130    AMD       165  157.17    B
219    219  2024-08-21  15:05:00.000000   26169    AMD       165  157.28    S
220    220  2024-09-09  13:35:00.000000   26757    AMD       189  137.60    B
221    221  2024-09-09  14:15:00.000000   26765    AMD       189  137.45    S
222    222  2024-09-09  14:55:00.000000   26773    AMD       189  137.27    B
223    223  2024-09-10  09:30:00.000000   26786    AMD       189  139.19    S