In [32]:
import pandas as pd
df = pd.read_csv("../data/SPY/SPY.USUSD_Candlestick_5_M_ASK_05.10.2022-05.10.2024.csv")
df=df[0:300]

df['Gmt time']=df["Gmt time"].str.replace(".000","")
df['Gmt time'] = pd.to_datetime(df['Gmt time'],format='%d.%m.%Y %H:%M:%S')

df2 = df[['Gmt time','Close','Open']]
df2 = df2.resample('d', on='Gmt time').mean().dropna(how='all')

df2

                 Close        Open
Gmt time
2022-10-05  377.023837  377.010955
2022-10-06  376.994000  376.994000

In [363]:
import pandas as pd

df = pd.read_csv("../data/SPY/SPY.USUSD_Candlestick_5_M_ASK_05.10.2022-05.10.2024.csv")
df=df[0:20000]

df['index']=df.index
df['Gmt time']=df["Gmt time"].str.replace(".000","")
df['datetime']=pd.to_datetime(df['Gmt time'],format='%d.%m.%Y %H:%M:%S')
df['YMD'] = df['datetime'].dt.strftime('%Y%m%d')

df['ema25'] = df.groupby(['YMD'])['Close'].apply(lambda x: x.ewm(span=25, adjust=False).mean()).droplevel(0)
df['isPriceActionAboveEma25'] = (df['Close'] > df['ema25'])

df['Tag2'] = df.groupby('YMD').isPriceActionAboveEma25.transform(
    lambda x: 'Invalid' if x[x==True].value_counts().shape[0] > 0 else 'Valid')

result = df[df["Tag2"]=='Valid']
result


#result = df[df["isPriceActionAboveEma25"]==True]
#result

#df['isTheDayAbove25Ema'] = df.groupby(['YMD'])['isPriceActionAboveEma25'].apply(lambda x: x==True).droplevel(0)


#result = df[df["isTheDayAbove25Ema"]==False]
#result = df[(df["isPriceActionAboveEma25"]==False) & (df["isTheDayAbove25Ema"]==True)]
#result

#funct1 = lambda pct: pct == True
#fun = funct1(df['isPriceActionAboveEma25'])
#val=df.loc[fun, 'YMD']
#fun
#ret= df['YMD'].isin(val)
#df[ret]
#df

#df['d'] = df.groupby('YMD').apply(lambda row: row.isPriceActionAboveEma25 + row.b + row.c, axis=1)

#df['isTheDayAbove25Ema'] = df.groupby(['YMD'])['isPriceActionAboveEma25'].apply(lambda x:  f"False" if x %2==False else f"True")

#df['isTheDayAbove25Ema'] = df.groupby('YMD').apply(lambda x: False if x[x["isPriceActionAboveEma25"]==False].count() > 0 else True)
#df['isTheDayAbove25Ema'] = df.groupby('YMD').filter(lambda group: group.isPriceActionAboveEma25 == False)

#result = df[(df["YMD"]=='20221005') & (df["isPriceActionAboveEma25"]==False)]
#result

,Gmt time,Open,High,Low,Close,Volume,index,datetime,YMD,ema25,isPriceActionAboveEma25,Tag2
0,05.10.2022 00:00:00,377.983,377.983,377.983,377.983,0.0,0,2022-10-05 00:00:00,20221005,377.983,False,Invalid
1,05.10.2022 00:05:00,377.983,377.983,377.983,377.983,0.0,1,2022-10-05 00:05:00,20221005,377.983,False,Invalid
2,05.10.2022 00:10:00,377.983,377.983,377.983,377.983,0.0,2,2022-10-05 00:10:00,20221005,377.983,False,Invalid
3,05.10.2022 00:15:00,377.983,377.983,377.983,377.983,0.0,3,2022-10-05 00:15:00,20221005,377.983,False,Invalid
4,05.10.2022 00:20:00,377.983,377.983,377.983,377.983,0.0,4,2022-10-05 00:20:00,20221005,377.983,False,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,15.01.2023 04:45:00,398.663,398.663,398.663,398.663,0.0,19995,2023-01-15 04:45:00,20230115,398.663,False,Valid
19996,15.01.2023 04:50:00,398.663,398.663,398.663,398.663,0.0,19996,2023-01-15 04:50:00,20230115,398.663,False,Valid
19997,15.01.2023 04:55:00,398.663,398.663,398.663,398.663,0.0,19997,2023-01-15 04:55:00,20230115,398.663,False,Valid
19998,15.01.2023 05:00:00,398.663,398.663,398.663,398.663,0.0,19998,2023-01-15 05:00:00,20230115,398.663,False,Valid
19999,15.01.2023 05:05:00,398.663,398.663,398.663,398.663,0.0,19999,2023-01-15 05:05:00,20230115,398.663,False,Valid