In [32]:
import pandas as pd
df = pd.read_csv("../data/SPY/SPY.USUSD_Candlestick_5_M_ASK_05.10.2022-05.10.2024.csv")
df=df[0:300]

df['Gmt time']=df["Gmt time"].str.replace(".000","")
df['Gmt time'] = pd.to_datetime(df['Gmt time'],format='%d.%m.%Y %H:%M:%S')

df2 = df[['Gmt time','Close','Open']]
df2 = df2.resample('d', on='Gmt time').mean().dropna(how='all')

df2

                 Close        Open
Gmt time
2022-10-05  377.023837  377.010955
2022-10-06  376.994000  376.994000

In [159]:
import pandas as pd

df = pd.read_csv("../data/SPY/SPY.USUSD_Candlestick_5_M_ASK_05.10.2022-05.10.2024.csv")
df=df[0:20000]

df['index']=df.index
df['Gmt time']=df["Gmt time"].str.replace(".000","")
df['datetime']=pd.to_datetime(df['Gmt time'],format='%d.%m.%Y %H:%M:%S')
df['YMD'] = df['datetime'].dt.strftime('%Y%m%d')

result = df.groupby(['YMD'])['Close'].apply(lambda x: x > x.ewm(span=25, adjust=False).mean())
df['isAbove'] = result.droplevel(0)  

df = df[df["isAbove"]==True]
df

,Gmt time,Open,High,Low,Close,Volume,index,datetime,YMD,isAbove
187,05.10.2022 15:35:00,372.564,373.453,372.513,373.334,25.4064,187,2022-10-05 15:35:00,20221005,True
193,05.10.2022 16:05:00,372.603,374.043,372.603,373.863,27.5823,193,2022-10-05 16:05:00,20221005,True
194,05.10.2022 16:10:00,373.843,374.743,373.763,374.333,27.7677,194,2022-10-05 16:10:00,20221005,True
195,05.10.2022 16:15:00,374.334,375.203,374.323,374.893,28.7745,195,2022-10-05 16:15:00,20221005,True
196,05.10.2022 16:20:00,374.903,374.954,374.514,374.823,24.2205,196,2022-10-05 16:20:00,20221005,True
...,...,...,...,...,...,...,...,...,...,...
19933,13.01.2023 23:35:00,398.663,398.663,398.663,398.663,0.0000,19933,2023-01-13 23:35:00,20230113,True
19934,13.01.2023 23:40:00,398.663,398.663,398.663,398.663,0.0000,19934,2023-01-13 23:40:00,20230113,True
19935,13.01.2023 23:45:00,398.663,398.663,398.663,398.663,0.0000,19935,2023-01-13 23:45:00,20230113,True
19936,13.01.2023 23:50:00,398.663,398.663,398.663,398.663,0.0000,19936,2023-01-13 23:50:00,20230113,True
19937,13.01.2023 23:55:00,398.663,398.663,398.663,398.663,0.0000,19937,2023-01-13 23:55:00,20230113,True